global:
  enabled: true
  tlsDisable: true

injector:
  enabled: false

server:
  ha:
    enabled: true
    replicas: 3
    apiAddr: "http://$(VAULT_K8S_POD_NAME).vault-internal:8200"
    raft:
      enabled: true
      setNodeId: true
      config: |        
        listener "tcp" {
          tls_disable   = true
          address         = "[::]:8200"
          cluster_address = "[::]:8201"
        }
        storage "raft" {
          path = "/vault/data"

          retry_join {
            auto_join             = "provider=k8s namespace=vault label_selector=\"component=server,app.kubernetes.io/instance=vault\""
            auto_join_scheme      = "http"
          }
        }

        service_registration "kubernetes" {}

        api_addr     = "http://HOSTNAME.vault-internal:8200"
        cluster_addr = "https://HOSTNAME.vault-internal:8201"        
        ui           = true

    readinessProbe:
      enabled: true
      path: "/v1/sys/health?standbyok=true"
    livenessProbe:
      enabled: true
      path: "/v1/sys/health?standbyok=true"
      initialDelaySeconds: 60

  service:
    annotations:
      cloud.google.com/backend-config: '{"default": "${vault_healthcheck}"}'

  ingress:
    enabled: true

    hosts:
      - host: "${fqdn}"
        paths: [/]

    annotations:
      kubernetes.io/ingress.global-static-ip-name: ${lb_ip_address_name}
ui:
  enabled: false
