apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .Values.backend_config_name }}
  namespace: {{ .Values.namespace }}
spec:
  healthCheck:
    timeoutSec: 5
    checkIntervalSec: 15
    healthyThreshold: 3
    unhealthyThreshold: 2
    type: HTTPS
    requestPath: /v1/sys/health
    port: 8200
  securityPolicy:
    name: {{ .Values.cloud_armor_security_policy_name }}
